version: '3.8'

services:
  backend:
    build: .
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.docker

    extra_hosts:
      - "host.docker.internal:host-gateway" # Esto ayuda a la compatibilidad en Linux
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: portfolio-network
    driver: bridge