spring.application.name=site
# ===============================================
# = DATABASE CONNECTION (POSTGRESQL)
# ===============================================
# La sintaxis es: ${NOMBRE_VARIABLE:valor_por_defecto}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================================
# = JPA CONFIGURATION
# ===============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# = HIBERNATE
# ===============================================
# En produccion, se recomienda cambiar esto a 'validate' o 'none'
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# ===============================================
# = JWT CONFIGURATION
# ===============================================
app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-milliseconds=${JWT_EXPIRATION}

# ===============================================
# = (OPC) SQL FORMAT
# ===============================================
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true