spring.application.name=site
# ===============================================
# = DATABASE CONNECTION (POSTGRESQL)
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=portfolio
spring.datasource.password=tpLy108p

# ===============================================
# = JPA CONFIGURATION
# ===============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# = HIBERNATE
# ===============================================
spring.jpa.hibernate.ddl-auto=update

# ===============================================
# = (OPC) SQL FORMAT
# ===============================================
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true