spring.application.name=site
# ===============================================
# = DATABASE CONNECTION (POSTGRESQL)
# ===============================================
# La sintaxis es: ${NOMBRE_VARIABLE:valor_por_defecto}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:portfolio}
spring.datasource.password=${DB_PASSWORD:secret_password}

# ===============================================
# = JPA CONFIGURATION
# ===============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# = HIBERNATE
# ===============================================
# En produccion, se recomienda cambiar esto a 'validate' o 'none'
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# ===============================================
# = JWT CONFIGURATION
# ===============================================
app.jwt-secret=${JWT_SECRET:your_jwt_secret_key_here_must_be_at_least_32_chars!!}
app.jwt-expiration-milliseconds=${JWT_EXPIRATION:604800000}

# ===============================================
# = (OPC) SQL FORMAT
# ===============================================
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true